export const companies = [
  {
    name: "AstroSoft Software Development Company",
    country: "Nigeria",
    skills: [
      "HTML",
      "CSS",
      "JavaScript",
      "React",
      "Tailwind",
      "Git",
      "React Native",
    ],
    role: "Frontend Developer",
    started: "2022",
    presenet: "2023",
    bio: "I help build and scale Astrosoft Frontend Projects. I bring concepts to life by seamlessly blending design and functionality. My journey in AstroSoft has been marked by a commitment to staying at the forefront of industry trends and technologies. I thrive on the challenges of responsive web design, ensuring that every project I tackle delivers a smooth and engaging user experience across diverse devices.",
  },
  {
    name: "Doiyo Exchange",
    country: "Nigeria",
    skills: [
      "HTML",
      "CSS",
      "JavaScript",
      "Tailwind",
      "Git",
      "NextJs",
      "Material UI",
      "Styled-Components",
    ],
    role: "Frontend Developer",
    started: "2023",
    presenet: "2024",
    bio: "As a frontend developer at Doiyo Exchange, I enhanced the user experience by designing an intuitive and responsive interface, ensuring seamless navigation for users of all levels. I implemented real-time cryptocurrency updates using WebSocket APIs and optimized the platform for speed and security, enabling fast, reliable trading and boosting customer satisfaction.",
  },
  {
    name: "Bingtellar",
    country: "Delaware US",
    skills: ["HTML", "CSS", "JavaScript", "Git", "React"],
    role: "Frontend Developer",
    started: "2023 October",
    presenet: "Present",
    bio: "As a frontend developer at Doiyo Exchange, I enhanced the user experience by designing an intuitive and responsive interface, ensuring seamless navigation for users of all levels. I implemented real-time cryptocurrency updates using WebSocket APIs and optimized the platform for speed and security, enabling fast, reliable trading and boosting customer satisfaction.",
  },
];
